import "./globals.css";
import { Inter } from "next/font/google";
import ToasterContext from "../app/context/ToasterContext";
import { Navbar } from "./(components)/navbar/Navbar";
import myUser from "./actions/getUser";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const myCurrentUser = await myUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterContext />
        <Navbar  myUser={myCurrentUser} />
        {children}
      </body>
    </html>
  );
}
